**Data Analytics**

1. Implement simple Naive Bayes classification algorithm using Python/R on iris.csv dataset.
2. Conpute confusion matrix to find TP, FP, TN, FN, accuracy Error Rate, Precision, Recall on given dataset.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Iris.csv")

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df.Species=df.Species.replace(['setosa', 'versicolor', 'virginica'],value=[0,1,2])

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
x=df.drop(['Species'],axis=1)
y=df['Species']
print(x)
print(y)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virgin

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)
print(xtrain)
print(ytrain)
print(xtest)
print(ytest)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137  138            6.4           3.1            5.5           1.8
84    85            5.4           3.0            4.5           1.5
27    28            5.2           3.5            1.5           0.2
127  128            6.1           3.0            4.9           1.8
132  133            6.4           2.8            5.6           2.2
..   ...            ...           ...            ...           ...
9     10            4.9           3.1            1.5           0.1
103  104            6.3           2.9            5.6           1.8
67    68            5.8           2.7            4.1           1.0
117  118            7.7           3.8            6.7           2.2
47    48            4.6           3.2            1.4           0.2

[120 rows x 5 columns]
137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
            ...       
9          Iris-setosa
103     Iri

In [ ]:
import sklearn
from sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB()
model=gaussian.fit(xtrain,ytrain)
print(model)


GaussianNB()


In [ ]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score,classification_report

In [ ]:
ytest_pred=gaussian.predict(xtest)
ytrain_pred=gaussian.predict(xtrain)
print(ytest_pred)
print(ytrain_pred)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa']
['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iri

In [ ]:
print("The accuracy for testing dataset is",accuracy_score(ytest, ytest_pred))

The accuracy for testing dataset is 1.0


In [ ]:
print("The accuracy for training dataset is",accuracy_score(ytrain,ytrain_pred))

The accuracy for training dataset is 0.9916666666666667


In [ ]:
print("The confusion matrix for testing dataset is",confusion_matrix(ytest,ytest_pred))

The confusion matrix for testing dataset is [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [ ]:
print("The confusion matrix for training dataset is",confusion_matrix(ytrain,ytrain_pred))

The confusion matrix for training dataset is [[39  0  0]
 [ 0 37  0]
 [ 0  1 43]]


In [ ]:
print("The precision score for training dataset is",precision_score(ytrain,ytrain_pred,average="micro"))

The precision score for training dataset is 0.9916666666666667


In [ ]:
print("The precision score for testing dataset is",precision_score(ytest,ytest_pred,average="micro"))

The precision score for testing dataset is 1.0


In [ ]:
print("The recall score for training dataset is",recall_score(ytrain,ytrain_pred,average="micro"))

The recall score for training dataset is 0.9916666666666667


In [ ]:
print("The recall score for testing dataset is",recall_score(ytest,ytest_pred,average="micro"))

The recall score for testing dataset is 1.0


In [ ]:
print("The classification report for training dataset is",classification_report(ytrain,ytrain_pred))

The classification report for training dataset is                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        39
Iris-versicolor       0.97      1.00      0.99        37
 Iris-virginica       1.00      0.98      0.99        44

       accuracy                           0.99       120
      macro avg       0.99      0.99      0.99       120
   weighted avg       0.99      0.99      0.99       120



In [ ]:
print("The classification report for testing dataset is",classification_report(ytest,ytest_pred))

The classification report for testing dataset is                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
print("The error rate for training dataset is",1-accuracy_score(ytrain,ytrain_pred))

The error rate for training dataset is 0.008333333333333304


In [ ]:
print("The error rate for testing dataset is",1-accuracy_score(ytrain,ytrain_pred))

The error rate for testing dataset is 0.008333333333333304
